---
displayName: Bash
description: Stack with environment ready to develop bash scripts.
tags: ["Bash", "Shell"]
icon: /images/che.svg
globalMemoryLimit: 2930Mi
links:
  self: /devfiles/bash/devfile.yaml
